FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Call Home

This is a mock API for the Call Home server so we can work as if it is already built

## Group Devices

## Get Devices [/api/devices/{id}]

A device object has the following attributes:

+ cameras - An array of Camera objects.
+ name - The device's name
+ status - The current status of the device (ie. online, offline, ...)
+ address - The address of the device
+ lat - The latitude of the device's location
+ lon - The longitude of the device's location
+ organizationPath - The location path of the device (ie. Canada/Ontario/Kanata)
+ lastCheckin - The UTC datetime of the most recent check-in (so we know how stale this data may be)


+ Parameters
    + id: b5084250-4b37-11e5-8184-752d1c0476b3 (required, string) - The ID of the device
    
### Get Device [GET]


+ Response 200 (application/json)

    + Body
    
            {
                "id": "b5084250-4b37-11e5-8184-752d1c0476b3",
                "name": "Amazing Connect #1",
                "status": "offline",
                "address": "221B Baker Street, London, England",
                "lat": -31.42,
                "lon": 41.99,
                "organizationPath": "Canada/Ontario/Kanata",
                "lastCheckin": "2015-08-25T20:11:46.370Z",
                "cameras": [
                    {
                        "id":"c5084250-4b37-11e5-8184-752d1c0476b3",
                        "name":"axis camera",
                        "thumbnail": "http://solink.aws.s3/12/thumbnails/hello.jpg"
                    },
                    {
                        "id":"d5084250-4b37-11e5-8184-752d1c0476b3",
                        "name":" POS camera",
                        "thumbnail": "http://solink.aws.s3/12/thumbnails/hello.jpg"
                    },
                    {
                        "id":"e5084250-4b37-11e5-8184-752d1c0476b3",
                        "name":"Door camera",
                        "thumbnail": "http://solink.aws.s3/12/thumbnails/hello.jpg"
                    }
                ]
            }

## List All Devices [/api/devices/{?filter%5Boffset%5D,filter%5Blimit%5D,filter%5Binclude%5D}]

+ Parameters
    + filter%5Boffset%5D: 5 (optional, number) - The offset of the device list to start paging from
    + filter%5Blimit%5D: 10 (optional, number) - The maximum number of devices to return
    + filter%5Binclude%5D: cameras (optional) - Relational data to include with the devices
    
### List all Devices [GET]

+ Response 200 (application/json)

    + Headers

            Link: </devices?offset=5>; rel="next"

    + Body
    
            [
                {
                    "id": "b5084250-4b37-11e5-8184-752d1c0476b3",
                    "name": "Amazing Connect #1",
                    "status": "offline",
                    "address": "221B Baker Street, London, England",
                    "lat": -31.42,
                    "lon": 41.99,
                    "organizationPath": "Canada/Ontario/Kanata",
                    "lastCheckin": "2015-08-25T20:11:46.370Z",
                    "cameras": [
                        {
                            "id":"c5084250-4b37-11e5-8184-752d1c0476b3",
                            "name":"camera 1",
                            "thumbnail": "http://solink.aws.s3/12/thumbnails/hello.jpg"
                        },
                        {
                            "id":"d5084250-4b37-11e5-8184-752d1c0476b3",
                            "name":"camera 2",
                            "thumbnail": "http://solink.aws.s3/12/thumbnails/hello.jpg"
                        },
                        {
                            "id":"e5084250-4b37-11e5-8184-752d1c0476b3",
                            "name":"camera 3",
                            "thumbnail": "http://solink.aws.s3/12/thumbnails/hello.jpg"
                        }
                    ]
                },
                {
                    "id": "b5084250-4b37-11e5-8184-752d1c0476b4",
                    "name": "Amazing Connect #2",
                    "status": "online",
                    "address": "221B Faker Street, London, England",
                    "lat": -311.42,
                    "lon": 411.99,
                    "organizationPath": "Canada/Ontario/Kanata",
                    "lastCheckin": "2015-08-25T20:11:46.370Z",
                    "cameras": [
                        {
                            "id":"a3084250-4b37-11e5-8184-752d1c0476b3",
                            "name":"camera 1",
                            "thumbnail": "http://solink.aws.s3/12/thumbnails/hello1.jpg"
                        },
                        {
                            "id":"a5084250-4b37-11e5-8184-752d1c0476b3",
                            "name":"camera 2",
                            "thumbnail": "http://solink.aws.s3/12/thumbnails/hello1.jpg"
                        },
                        {
                            "id":"b3084250-4b37-11e5-8184-752d1c0476b3",
                            "name":"camera 3",
                            "thumbnail": "http://solink.aws.s3/12/thumbnails/hello1.jpg"
                        }
                    ]
                },
                {
                    "id": "c3084250-4b37-11e5-8184-752d1c0476b3",
                    "name": "Not So Amazing Connect #1",
                    "status": "online",
                    "address": "390 March Road, Ottawa, Ontario, Canada",
                    "lat": 31.42,
                    "lon": 41.99,
                    "organizationPath": "Canada/Ontario/Kanata",
                    "lastCheckin": "2015-08-25T20:11:46.370Z",
                    "cameras": [
                        {
                            "id":"53",
                            "name":"camera 1",
                            "thumbnail": "http://solink.aws.s3/12/thumbnails/hello555.jpg"
                        },
                        {
                            "id":"54",
                            "name":"camera 2",
                            "thumbnail": "http://solink.aws.s3/12/thumbnails/hello555.jpg"
                        },
                        {
                            "id":"55",
                            "name":"camera 3",
                            "thumbnail": "http://solink.aws.s3/12/thumbnails/hello555.jpg"
                        }
                    ]
                },
                {
                    "id": "d3084250-4b37-11e5-8184-752d1c0476b3",
                    "name": "Not So Amazing Connect #2",
                    "status": "online",
                    "address": "221B Baker Street, London, England",
                    "lat": -31.142,
                    "lon": 41.939,
                    "organizationPath": "Canada/Ontario/Kanata",
                    "lastCheckin": "2015-08-25T20:11:46.370Z",
                    "cameras": [
                        {
                            "id":"43",
                            "name":"camera 1",
                            "thumbnail": "http://solink.aws.s3/12/thumbnails/hello33.jpg"
                        },
                        {
                            "id":"44",
                            "name":"camera 2",
                            "thumbnail": "http://solink.aws.s3/12/thumbnails/hello44.jpg"
                        },
                        {
                            "id":"45",
                            "name":"camera 3",
                            "thumbnail": "http://solink.aws.s3/12/thumbnails/hello11.jpg"
                        }
                    ]
                },
                {
                    "id": "e3084250-4b37-11e5-8184-752d1c0476b3",
                    "name": "Not So Amazing Connect #3",
                    "status": "offline",
                    "address": "123 Sesame Street, Paris, France",
                    "lat": -11.42,
                    "lon": 11.99,
                    "organizationPath": "Canada/Quebec/Nepean",
                    "lastCheckin": "2015-08-25T20:11:46.370Z",
                    "cameras": [
                        {
                            "id":"13",
                            "name":"camera 1",
                            "thumbnail": "http://solink.aws.s3/12/thumbnails/hello5.jpg"
                        },
                        {
                            "id":"14",
                            "name":"camera 2",
                            "thumbnail": "http://solink.aws.s3/12/thumbnails/hello3.jpg"
                        },
                        {
                            "id":"15",
                            "name":"camera 3",
                            "thumbnail": "http://solink.aws.s3/12/thumbnails/hello7.jpg"
                        }
                    ]
                },
            ]
            
## List All Cameras on a Device [/api/devices/{id}/cameras]

+ Parameters
    + id: a3084250-4b37-11e5-8184-752d1c0476b3 (required, string) - The id of the device
    
### List all cameras on a device [GET]

+ Response 200 (application/json)

    + Body
    
            [
                {
                    "id":"a3084250-4b37-11e5-8184-752d1c0476b3",
                    "name":"axis camera",
                    "thumbnail": "http://solink.aws.s3/12/thumbnails/hello.jpg"
                },
                {
                    "id":"b3084250-4b37-11e5-8184-752d1c0476b3",
                    "name":" POS camera",
                    "thumbnail": "http://solink.aws.s3/12/thumbnails/hello.jpg"
                },
                {
                    "id":"c3084250-4b37-11e5-8184-752d1c0476b3",
                    "name":"Door camera",
                    "thumbnail": "http://solink.aws.s3/12/thumbnails/hello.jpg"
                }
            ]
                

## Group Licenses

## Activate [/api/licenses/activate]

When installing a Connect device, a license key is provided.  Providing this license key will hit this endpoint, which activates the license for that device and adds it to our /devices repository.

### Activate [POST]
+ Request (application/json)

        {
            "key": "161bc25962da8fed6d2f59922fb642aa"
        }

+ Response 200 (application/json)

        {
            authToken: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBfbWV0YWRhdGEiOnsidGVuYW50X2lkIjoiMSIsInVzZXJfdHlwZSI6IlN1cGVyQWRtaW4ifSwiZW1haWwiOiJjd2hpdGVuKzFAc29saW5rY29ycC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImlzcyI6Imh0dHBzOi8vc29saW5rLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1NWE2ODVjMjQ4OTdiM2FiMTAyNTUzMjgiLCJhdWQiOiI1UjlpREtpUTduWUNHT0phQkRyUGJlc013bmtHajdpaCIsImV4cCI6MTQzNzc5MzA4MCwiaWF0IjoxNDM3NzU3MDgwfQ.8yCltCoXpjAumpSiAZpFl55-rWwKTdZgQ8pOjFUCLsY",
            refreshToken: "W4WhwYpXTBeBYuuNz7zBSBf8zZbkazQlLWkRmvaYMoSAM",
            deviceId: "A4af23bij"
        }

## Group Authentication

## Login [/api/auth/login]

A user or connect device will post to the /auth/login endpoint to get a valid JWT token for future calls.

### Login [POST]
+ Request (application/json)

        {
            "username": "cwhiten@solinkcorp.com",
            "password": "test"
        }

+ Response 200 (application/json)

        {
            auth_token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBfbWV0YWRhdGEiOnsidGVuYW50X2lkIjoiMSIsInVzZXJfdHlwZSI6IlN1cGVyQWRtaW4ifSwiZW1haWwiOiJjd2hpdGVuKzFAc29saW5rY29ycC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImlzcyI6Imh0dHBzOi8vc29saW5rLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1NWE2ODVjMjQ4OTdiM2FiMTAyNTUzMjgiLCJhdWQiOiI1UjlpREtpUTduWUNHT0phQkRyUGJlc013bmtHajdpaCIsImV4cCI6MTQzNzc5MzA4MCwiaWF0IjoxNDM3NzU3MDgwfQ.8yCltCoXpjAumpSiAZpFl55-rWwKTdZgQ8pOjFUCLsY",
            refresh_token: "W4WhwYpXTBeBYuuNz7zBSBf8zZbkazQlLWkRmvaYMoSAM",
            aws: {
                AccessKeyId: "ASIAIE3VWYBHAN32YG5Q",
                SecretAccessKey: "UbILm6V9ip0gyUpw6kqDcet+PGFwrjBhmPa+Z6p2",
                SessionToken: "AQoDYXdzENr//////////wEawALgJc/SxMUbsxgIL5CGQcoGQmxF5wpV8ZuWQtwDYGngPfrXCHxoknbwxjwQOJPaK6N2rFtKoPw4ojJon1K9BQlNZnUQ4NSuPmTqDLZdltS+nrlUdZ/U8RWdFhoDtrJLL/aBsHBlymLPIR//JcuiCMnWZDtPpOIZVK92wZKllMunfnnpVz9LN/X6jkeX2NhMYRK+Q2dTH0Z7UuOgK+UMTW1/ayFECDGrVCctkmdR1Rr/cVA0yq8zF4k/SYar5WZIWQ1YLvSHT57/jD/lAUBOuBQ64gMwvXw8ptsRpl1c0xjWZn4azrMBz+FJAs2OTbcrl/arUF3YVLttH+aEIxHMamGYbUxqq3e7LOjKvnJbWFVWfdsrRaWMyaEIPYbVKOodRtlcsD+9p2qXtBr0eB48hBggxoir+P9yGNFeprgG7s/e/SCZ3cmtBQ=="
            }-
        }
        
## Validate [/api/auth/validate]

Validate whether a given JWT token is valid (not expired, matches secret, not revoked).
Returns a 200 if valid.  Otherwise, returns a 401.

### Validate [POST]
+ Request (application/json)

        {
            "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBfbWV0YWRhdGEiOnsidGVuYW50X2lkIjoiMSIsInVzZXJfdHlwZSI6IlN1cGVyQWRtaW4ifSwiZW1haWwiOiJjd2hpdGVuKzFAc29saW5rY29ycC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImlzcyI6Imh0dHBzOi8vc29saW5rLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1NWE2ODVjMjQ4OTdiM2FiMTAyNTUzMjgiLCJhdWQiOiI1UjlpREtpUTduWUNHT0phQkRyUGJlc013bmtHajdpaCIsImV4cCI6MTQzNzc5MzA4MCwiaWF0IjoxNDM3NzU3MDgwfQ.8yCltCoXpjAumpSiAZpFl55-rWwKTdZgQ8pOjFUCLsY",
        }

+ Response 200 (application/json)

        {
        }

## Refresh [/api/auth/refresh]

Generate a new authentication token from a user's refresh token.

### Refresh [POST]
+ Request (application/json)

        {
            "token": "W4WhwYpXTBeBYuuNz7zBSBf8zZbkazQlLWkRmvaYMoSAM"
        }

+ Response 200 (application/json)

        {
            "auth_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBfbWV0YWRhdGEiOnsidGVuYW50X2lkIjoiMSIsInVzZXJfdHlwZSI6IlN1cGVyQWRtaW4ifSwiZW1haWwiOiJjd2hpdGVuKzFAc29saW5rY29ycC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImlzcyI6Imh0dHBzOi8vc29saW5rLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1NWE2ODVjMjQ4OTdiM2FiMTAyNTUzMjgiLCJhdWQiOiI1UjlpREtpUTduWUNHT0phQkRyUGJlc013bmtHajdpaCIsImV4cCI6MTQzNzc5MzA4MCwiaWF0IjoxNDM3NzU3MDgwfQ.8yCltCoXpjAumpSiAZpFl55-rWwKTdZgQ8pOjFUCLsY"
        }
        
## Set password [/api/auth/setpassword]

A request from the platform is sent out with user's current email and new password

### Change Password [POST]
+ Request (application/json)

        {
            "email": "isharif@solinkcorp.com",
            "password": "new password"
        }

+ Response 202
