 FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Call Home

This is a mock API for the Call Home server so we can work as if it is already built

## Group Customers

## List Users [/api/customers/{id}/listUsers]

List all of the users under a given tenant.

### List Users [GET]

+ Response 200 (application/json)

        {
            "users":[
                {
                    "email":"cwhiten+jumanji@solinkcorp.com",
                    "email_verified":true,
                    "user_id":"auth0|56bb758503dd760e71a57c96",
                    "picture":"https://s.gravatar.com/avatar/908b60832e2bd6efc712b3bfa7fcd7bd?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fcw.png",
                    "nickname":"cwhiten+jumanji",
                    "identities":[
                        {
                            "user_id":"56bb758503dd760e71a57c96",
                            "provider":"auth0",
                            "connection":"Username-Password-Authentication",
                            "isSocial":false
                        }
                    ],
                    "updated_at":"2016-02-16T16:24:21.198Z",
                    "created_at":"2016-02-10T17:38:13.358Z",
                    "last_password_reset":"2016-02-12T16:33:55.688Z",
                    "name":"cwhiten+jumanji@solinkcorp.com",
                    "last_login":"2016-02-12T16:35:14.883Z",
                    "logins_count":1,
                    "app_metadata":{
                        "tenantId":"58e1ae10-c532-11e5-b7f4-19f29daa641d",
                        "userType":"admin",
                        "devices":[
                            "7b43b990-c536-11e5-8f73-4bebc88006af",
                            "8edc0d40-c536-11e5-8f73-4bebc88006af"
                        ]
                    },
                    "user_metadata":{
                        "wrtc": "false",
                        "defaultToHD":"false"
                    }
                },
                {
                    "email":"cwhiten+stripedemo@solinkcorp.com",
                    "email_verified":true,
                    "user_id":"auth0|56a924c536e4c4fb3922c641",
                    "picture":"https://s.gravatar.com/avatar/245652a80c146e2ad3c2f62aa51f14e0?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fcw.png",
                    "nickname":"cwhiten+stripedemo",
                    "identities":[
                        {
                            "user_id":"56a924c536e4c4fb3922c641",
                            "provider":"auth0",
                            "connection":"Username-Password-Authentication",
                            "isSocial":false
                        }
                    ],
                    "updated_at":"2016-02-16T15:35:35.269Z",
                    "created_at":"2016-01-27T20:12:53.965Z",
                    "last_password_reset":"2016-02-10T15:37:14.502Z",
                    "name":"cwhiten+stripedemo@solinkcorp.com",
                    "last_ip":"52.35.201.87",
                    "last_login":"2016-02-10T15:37:35.209Z",
                    "logins_count":4,
                    "app_metadata":{
                        "tenantId":"58e1ae10-c532-11e5-b7f4-19f29daa641d",
                        "userType":"admin",
                        "devices":[
                            "f8ee3f10-c535-11e5-8f73-4bebc88006af"
                        ]
                    },
                    "user_metadata":{
                        "wrtc":"true",
                        "defaultToHD":"true"
                    }
                },
                {
                    "email":"cwhiten+test981@solinkcorp.com",
                    "email_verified":true,
                    "user_id":"auth0|56bb760e1f3084f139ffee35",
                    "picture":"https://s.gravatar.com/avatar/3618381e3889e1267616f4c76ce0eb6b?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fcw.png",
                    "identities":[
                        {
                            "user_id":"56bb760e1f3084f139ffee35",
                            "provider":"auth0",
                            "connection":"Username-Password-Authentication",
                            "isSocial":false
                        }
                    ],
                    "updated_at":"2016-02-10T17:40:30.533Z",
                    "created_at":"2016-02-10T17:40:30.533Z",
                    "app_metadata":{
                        "tenantId":"58e1ae10-c532-11e5-b7f4-19f29daa641d",
                        "userType":"admin"
                    }
                },
                {
                    "email":"cwhiten+anothertest@solinkcorp.com",
                    "email_verified":true,
                    "user_id":"auth0|56bb763603dd760e71a57d30",
                    "picture":"https://s.gravatar.com/avatar/1a719b8ac72d98d2a6ce82d3f6b7bb2f?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fcw.png",
                    "identities":[
                        {
                            "user_id":"56bb763603dd760e71a57d30",
                            "provider":"auth0",
                            "connection":"Username-Password-Authentication",
                            "isSocial":false
                        }
                    ],
                    "updated_at":"2016-02-10T17:41:10.068Z",
                    "created_at":"2016-02-10T17:41:10.068Z",
                    "app_metadata":{
                        "tenantId":"58e1ae10-c532-11e5-b7f4-19f29daa641d",
                        "userType":"standard"
                    }
                },
                {
                    "email":"hello@world.com",
                    "email_verified":true,
                    "user_id":"auth0|56bb7b68ea988c1753045ee5",
                    "picture":"https://s.gravatar.com/avatar/4b3cdf9adfc6258a102ab90eb64565ea?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fhe.png",
                    "identities":[
                        {
                            "user_id":"56bb7b68ea988c1753045ee5",
                            "provider":"auth0",
                            "connection":"Username-Password-Authentication",
                            "isSocial":false
                        }
                    ],
                    "updated_at":"2016-02-10T18:03:20.254Z",
                    "created_at":"2016-02-10T18:03:20.254Z",
                    "app_metadata":{
                        "tenantId":"58e1ae10-c532-11e5-b7f4-19f29daa641d",
                        "userType":"admin"
                    }
                },
                {
                    "email":"test12@solinkcorp.com",
                    "email_verified":true,
                    "user_id":"auth0|56bb7c3bea988c1753045f92",
                    "picture":"https://s.gravatar.com/avatar/decd95c7e9cb13e41cfc49b5912c1b45?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fte.png",
                    "identities":[
                        {
                            "user_id":"56bb7c3bea988c1753045f92",
                            "provider":"auth0",
                            "connection":"Username-Password-Authentication",
                            "isSocial":false
                        }
                    ],
                    "updated_at":"2016-02-10T18:06:51.342Z",
                    "created_at":"2016-02-10T18:06:51.342Z",
                    "app_metadata":{
                        "tenantId":"58e1ae10-c532-11e5-b7f4-19f29daa641d",
                        "userType":"admin"
                    }
                }
            ]
        }


## Group Devices

## Get Devices [/api/devices/{id}]

A device object has the following attributes:

+ cameras - An array of Camera objects.
+ name - The device's name
+ status - The current status of the device (ie. online, offline, ...)
+ address - The address of the device
+ location - The latitude and longitude of the device's location
+ organizationPath - The location path of the device (ie. Canada/Ontario/Kanata)
+ lastCheckin - The UTC datetime of the most recent check-in (so we know how stale this data may be)
+ username - The username to authenticate with the device
+ password - The password to authenticate with the device
+ ipAddress - The IP address of the device


+ Parameters
    + id: b5084250-4b37-11e5-8184-752d1c0476b3 (required, string) - The ID of the device

### Get Device [GET]

+ Response 200 (application/json)

    + Body

            {
                "id": "b5084250-4b37-11e5-8184-752d1c0476b3",
                "guid": null,
                "name": "Store #210",
                "status": "offline",
                "address": "St. John's, NL, Canada",
                "phoneNumber": "2268884444",
                "organizationPath": "Canada/Ontario/Ottawa",
                "location": {
                    "lat": 46.1234586,
                    "lng": 7.211228
                },
                "osVersion": "4.2.0",
                "currentSoftwareVersion": "4.0.11",
                "signallingServerUrl": "http://localhost:3000",
                "model": "TS-X53U",
                "modelName": "Rackmount Turbo NAS",
                "deviceCapacity": "832.31",
                "availableCapacity": "400.01",
                "checkinInterval": 120,
                "lastCheckin": "2016-01-25T14:49:19.588Z",
                "customerId": "b4132x23-8y42-00t1-75y4-b1234u545c3c",
                "softwareVersionId": "99a1d2f0-be3d-11e5-a6d3-75b5c9a8178b",
                "username": "solink-local",
                "password": "__connect__",
                "ipAddress": "10.126.140.203",
                "vmsPort": 18080,
                "overrideIpAddress": "192.168.1.1" ,
                "overrideConnectPort": 8080,
                "overrideVmsPort": 8081,
                "overrideCheckinPort": 8082,
                "overrideUploaderPort": 8082,
                "overrideListenerPort": 8083,
                "overrideConfigForwardPort": 8084,
                "localIP": "10.1.1.2"
            }

            
## Get Device With Camera [/api/devices{id}{?filter%5Binclude%5D}]

+ Parameters
    + id: b5084250-4b37-11e5-8184-752d1c0476b3 (required, string) - The ID of the device
    + filter%5Binclude%5D: cameras (optional) - Relational data to include with the devices

### Get Device With Camera [GET]


+ Response 200 (application/json)
    
    + Body

            {
                "id": "b5084250-4b37-11e5-8184-752d1c0476b3",
                "guid": null,
                "name": "Store #210",
                "status": "offline",
                "address": "St. John's, NL, Canada",
                "phoneNumber": "2268884444",
                "organizationPath": "Canada/Ontario/Ottawa",
                "location": {
                    "lat": 46.1234586,
                    "lng": 7.211228
                },
                "osVersion": "4.2.0",
                "currentSoftwareVersion": "4.0.11",
                "signallingServerUrl": "http://localhost:3000",
                "model": "TS-X53U",
                "modelName": "Rackmount Turbo NAS",
                "deviceCapacity": "832.31",
                "availableCapacity": "400.01",
                "checkinInterval": 120,
                "lastCheckin": "2016-01-25T14:49:19.588Z",
                "customerId": "b4132x23-8y42-00t1-75y4-b1234u545c3c",
                "softwareVersionId": "99a1d2f0-be3d-11e5-a6d3-75b5c9a8178b",
                "username": "solink-local",
                "password": "__connect__",
                "ipAddress": "10.126.140.203",
                "vmsPort": 18080,
                "overrideIpAddress": "192.168.1.1" ,
                "overrideConnectPort": 8080,
                "overrideVmsPort": 8081,
                "overrideCheckinPort": 8082,
                "overrideUploaderPort": 8082,
                "overrideListenerPort": 8083,
                "overrideConfigForwardPort": 8084,
                "localIP": "10.1.1.2",
                "cameras": [
                     {
                         "id":"c5084250-4b37-11e5-8184-752d1c0476b3",
                         "name":"axis camera",
                         "thumbnail": "12/thumbnails/hello.jpg",
                         "streams": [
                             {
                                 "id": "streamabc",
                                 "name": "HD",
                                 "earliestSegmentDate": 1450211609000,
                                 "latestSegmentDate": 1550211609000
                             },
                             {
                                 "id": "streamdef",
                                 "name": "SD",
                                 "earliestSegmentDate": 1450211609000,
                                 "latestSegmentDate": 1550211609000
                             }
                         ]
                     },
                     {
                         "id":"d5084250-4b37-11e5-8184-752d1c0476b3",
                         "name":" POS camera",
                         "thumbnail": "12/thumbnails/hello.jpg",
                         "streams": [
                             {
                                 "id": "streamabc",
                                 "name": "HD",
                                 "earliestSegmentDate": 1450211609000,
                                 "latestSegmentDate": 1550211609000
                             },
                             {
                                 "id": "streamdef",
                                 "name": "SD",
                                 "earliestSegmentDate": 1450211609000,
                                 "latestSegmentDate": 1550211609000
                             }
                         ]
                     },
                     {
                         "id":"e5084250-4b37-11e5-8184-752d1c0476b3",
                         "name":"Door camera",
                         "thumbnail": "12/thumbnails/hello.jpg",
                         "streams": [
                            {
                                 "id": "streamabc",
                                 "name": "HD",
                                 "earliestSegmentDate": 1450211609000,
                                 "latestSegmentDate": 1550211609000
                             },
                             {
                                 "id": "streamdef",
                                 "name": "SD",
                                 "earliestSegmentDate": 1450211609000,
                                 "latestSegmentDate": 1550211609000
                             }
                         ]
                     }
                 ]
            }

## List All Devices [/api/devices{?filter%5Boffset%5D,filter%5Blimit%5D,filter%5Binclude%5D}]

+ Parameters
    + filter%5Boffset%5D: 5 (optional, number) - The offset of the device list to start paging from
    + filter%5Blimit%5D: 10 (optional, number) - The maximum number of devices to return
    + filter%5Binclude%5D: cameras (optional) - Relational data to include with the devices

### List all Devices [GET]

+ Response 200 (application/json)

    + Headers

            Link: </devices?offset=5>; rel="next"

    + Body

            [
                {
                    "id": "b5084250-4b37-11e5-8184-752d1c0476b3",
                    "name": "Amazing Connect #1",
                    "status": "offline",
                    "address": "221B Baker Street, London, England",
                    "location": {
                        "lat": -31.42,
                        "lng": 41.99
                    },
                    "organizationPath": "Canada/Ontario/Kanata",
                    "lastCheckin": "2015-08-25T20:11:46.370Z",
                    "username": "christopher",
                    "password": "test",
                    "ipAddress": "54.1.1.3",
                    "localIP": "10.1.1.2",
                    "cameras": [
                        {
                            "id":"c5084250-4b37-11e5-8184-752d1c0476b3",
                            "name":"camera 1",
                            "thumbnail": "12/thumbnails/hello.jpg",
                            "streams": [
                                {
                                    "id": "streamabc",
                                    "name": "HD",
                                    "earliestSegmentDate": 1450211609000,
                                    "latestSegmentDate": 1550211609000
                                },
                                {
                                    "id": "streamdef",
                                    "name": "SD",
                                    "earliestSegmentDate": 1450211609000,
                                    "latestSegmentDate": 1550211609000
                                }
                            ]
                        },
                        {
                            "id":"d5084250-4b37-11e5-8184-752d1c0476b3",
                            "name":"camera 2",
                            "thumbnail": "12/thumbnails/hello.jpg",
                            "streams": [
                                {
                                    "id": "streamabc",
                                    "name": "HD",
                                    "earliestSegmentDate": 1450211609000,
                                    "latestSegmentDate": 1550211609000
                                },
                                {
                                    "id": "streamdef",
                                    "name": "SD",
                                    "earliestSegmentDate": 1450211609000,
                                    "latestSegmentDate": 1550211609000
                                }
                            ]
                        },
                        {
                            "id":"e5084250-4b37-11e5-8184-752d1c0476b3",
                            "name":"camera 3",
                            "thumbnail": "12/thumbnails/hello.jpg",
                            "streams": [
                                {
                                    "id": "streamabc",
                                    "name": "HD",
                                    "earliestSegmentDate": 1450211609000,
                                    "latestSegmentDate": 1550211609000
                                },
                                {
                                    "id": "streamdef",
                                    "name": "SD",
                                    "earliestSegmentDate": 1450211609000,
                                    "latestSegmentDate": 1550211609000
                                }
                            ]
                        }
                    ]
                },
                {
                    "id": "b5084250-4b37-11e5-8184-752d1c0476b4",
                    "name": "Amazing Connect #2",
                    "status": "online",
                    "address": "221B Faker Street, London, England",
                    "location": {
                        "lat": -311.42,
                        "lng": 411.99
                    },
                    "organizationPath": "Canada/Ontario/Kanata",
                    "lastCheckin": "2015-08-25T20:11:46.370Z",
                    "username": "christopher",
                    "password": "test",
                    "ipAddress": "54.1.1.3",
                    "localIP": "10.1.1.3",
                    "cameras": [
                        {
                            "id":"a3084250-4b37-11e5-8184-752d1c0476b3",
                            "name":"camera 1",
                            "thumbnail": "12/thumbnails/hello1.jpg"
                        },
                        {
                            "id":"a5084250-4b37-11e5-8184-752d1c0476b3",
                            "name":"camera 2",
                            "thumbnail": "12/thumbnails/hello1.jpg",
                            "streams": [
                                {
                                    "id": "streamabc",
                                    "name": "HD",
                                    "earliestSegmentDate": 1450211609000,
                                    "latestSegmentDate": 1550211609000
                                },
                                {
                                    "id": "streamdef",
                                    "name": "SD",
                                    "earliestSegmentDate": 1450211609000,
                                    "latestSegmentDate": 1550211609000
                                }
                            ]
                        },
                        {
                            "id":"b3084250-4b37-11e5-8184-752d1c0476b3",
                            "name":"camera 3",
                            "thumbnail": "12/thumbnails/hello1.jpg",
                            "streams": [
                                {
                                    "id": "streamabc",
                                    "name": "HD",
                                    "earliestSegmentDate": 1450211609000,
                                    "latestSegmentDate": 1550211609000
                                },
                                {
                                    "id": "streamdef",
                                    "name": "SD",
                                    "earliestSegmentDate": 1450211609000,
                                    "latestSegmentDate": 1550211609000
                                }
                            ]
                        }
                    ]
                },
                {
                    "id": "c3084250-4b37-11e5-8184-752d1c0476b3",
                    "name": "Not So Amazing Connect #1",
                    "status": "online",
                    "address": "390 March Road, Ottawa, Ontario, Canada",
                    "location": {
                        "lat": -31.42,
                        "lng": 41.99
                    },
                    "organizationPath": "Canada/Ontario/Kanata",
                    "lastCheckin": "2015-08-25T20:11:46.370Z",
                    "username": "christopher",
                    "password": "test",
                    "ipAddress": "54.1.1.3",
                    "localIP": "10.1.1.4",
                    "cameras": [
                        {
                            "id":"53",
                            "name":"camera 1",
                            "thumbnail": "12/thumbnails/hello555.jpg"
                        },
                        {
                            "id":"54",
                            "name":"camera 2"
                        },
                        {
                            "id":"55",
                            "name":"camera 3",
                            "thumbnail": "12/thumbnails/hello555.jpg",
                            "streams": [
                                {
                                    "id": "streamabc",
                                    "name": "HD",
                                    "earliestSegmentDate": 1450211609000,
                                    "latestSegmentDate": 1550211609000
                                },
                                {
                                    "id": "streamdef",
                                    "name": "SD",
                                    "earliestSegmentDate": 1450211609000,
                                    "latestSegmentDate": 1550211609000
                                }
                            ]
                        }
                    ]
                },
                {
                    "id": "d3084250-4b37-11e5-8184-752d1c0476b3",
                    "name": "Not So Amazing Connect #2",
                    "status": "online",
                    "address": "221B Baker Street, London, England",
                    "location": {
                        "lat": -31.421,
                        "lng": 41.991
                    },
                    "organizationPath": "Canada/Ontario/Kanata",
                    "lastCheckin": "2015-08-25T20:11:46.370Z",
                    "username": "christopher",
                    "password": "test",
                    "ipAddress": "54.1.1.3",
                    "localIP": "10.1.1.6",
                    "cameras": [
                        {
                            "id":"43",
                            "name":"camera 1"
                        },
                        {
                            "id":"44",
                            "name":"camera 2"
                        },
                        {
                            "id":"45",
                            "name":"camera 3",
                            "streams": [
                                {
                                    "id": "streamabc",
                                    "name": "HD",
                                    "earliestSegmentDate": 1450211609000,
                                    "latestSegmentDate": 1550211609000
                                },
                                {
                                    "id": "streamdef",
                                    "name": "SD",
                                    "earliestSegmentDate": 1450211609000,
                                    "latestSegmentDate": 1550211609000
                                }
                            ]
                        }
                    ]
                },
                {
                    "id": "e3084250-4b37-11e5-8184-752d1c0476b3",
                    "name": "Not So Amazing Connect #3",
                    "status": "offline",
                    "address": "123 Sesame Street, Paris, France",
                    "location": {
                        "lat": -11.42,
                        "lng": 11.99
                    },
                    "organizationPath": "Canada/Quebec/Nepean",
                    "lastCheckin": "2015-08-25T20:11:46.370Z",
                    "username": "christopher",
                    "password": "test",
                    "ipAddress": "54.1.1.3",
                    "localIP": "10.1.1.8",
                    "cameras": [
                        {
                            "id":"13",
                            "name":"camera 1",
                            "thumbnail": "http://solink.aws.s3/12/thumbnails/hello5.jpg"
                        },
                        {
                            "id":"14",
                            "name":"camera 2",
                            "thumbnail": "http://solink.aws.s3/12/thumbnails/hello3.jpg"
                        },
                        {
                            "id":"15",
                            "name":"camera 3",
                            "thumbnail": "http://solink.aws.s3/12/thumbnails/hello7.jpg"
                        }
                    ]
                },
            ]



## List All Cameras on a Device [/api/devices/{id}/cameras]

+ Parameters
    + id: a3084250-4b37-11e5-8184-752d1c0476b3 (required, string) - The id of the device

### List all cameras on a device [GET]

+ Response 200 (application/json)

    + Body

            [
                {
                    "id":"a3084250-4b37-11e5-8184-752d1c0476b3",
                    "name":"axis camera",
                    "thumbnail": "http://solink.aws.s3/12/thumbnails/hello.jpg",
                    "streams": [
                        {
                            "id": "streamabc",
                            "name": "HD",
                            "earliestSegmentDate": 1450211609000,
                            "latestSegmentDate": 1550211609000
                        },
                        {
                            "id": "streamdef",
                            "name": "SD",
                            "earliestSegmentDate": 1450211609000,
                            "latestSegmentDate": 1550211609000
                        }
                    ]
                },
                {
                    "id":"b3084250-4b37-11e5-8184-752d1c0476b3",
                    "name":" POS camera",
                    "thumbnail": "http://solink.aws.s3/12/thumbnails/hello.jpg",
                    "streams": [
                        {
                            "id": "streamabc",
                            "name": "HD",
                            "earliestSegmentDate": 1450211609000,
                            "latestSegmentDate": 1550211609000
                        },
                        {
                            "id": "streamdef",
                            "name": "SD",
                            "earliestSegmentDate": 1450211609000,
                            "latestSegmentDate": 1550211609000
                        }
                    ]
                },
                {
                    "id":"c3084250-4b37-11e5-8184-752d1c0476b3",
                    "name":"Door camera",
                    "thumbnail": "http://solink.aws.s3/12/thumbnails/hello.jpg",
                    "streams": [
                        {
                            "id": "streamabc",
                            "name": "HD",
                            "earliestSegmentDate": 1450211609000,
                            "latestSegmentDate": 1550211609000
                        },
                        {
                            "id": "streamdef",
                            "name": "SD",
                            "earliestSegmentDate": 1450211609000,
                            "latestSegmentDate": 1550211609000
                        }
                    ]
                }
            ]

## Checkin a Device [/api/devices/{id}/checkin]


+ Parameters
    + id: a3084250-4b37-11e5-8184-752d1c0476b3 (required, string) - The id of the device, required in the url only

### Checkin a device [POST]

+ Request (application/json)

            {
                "data":
                    {
                        "timestamp": "1449775377473",
                        "name": "20 E Chicago Ave",
                        "address": "20 E Chicago Ave, Chicago, IL 60611, USA",
                        "location": {
                            "lat": 41.8969068,
                            "lng": -87.6274042
                        },
                        "password": "__connect__",
                        "username": "solink-local",
                        "locationName": "RR Chicago Avenue",
                        "posInformation": [
                            {
                                "evt": "motion",
                                "url": "http://localhost:8080/?username=solink-local&password=__connect__",
                                "name": "Motion",
                                "type": "socketio",
                                "error": null,
                                "posId": 0,
                                "status": "online",
                                "filter_id": "Bu2NuOPsjK3r4tLF"
                            }
                        ],
                        "organizationPath": "United States/Illinois/Chicago",
                        "cameraInformation": [
                            {
                                "ip": "10.10.0.123",
                                "name": "Storage",
                                "status": "online",
                                "streams": [
                                    {
                                        "id": "25790730-dc54-45dd-e379-bda82fdfe540",
                                        "url": "rtsp://admin:admin@192.168.0.107/video1enc2",
                                        "name": "SD",
                                        "retention": "",
                                        "latestThumb": "1449775341000_16216"
                                    },
                                    {
                                        "id": "3db6dae2-912c-4ff9-fa79-470c8b41615d",
                                        "url": "rtsp://admin:admin@192.168.0.107/video1enc1",
                                        "name": "HD",
                                        "retention": "",
                                        "latestThumb": "1449775336000_17417"
                                    }
                                ],
                                "cameraId": "CsfA4LyDGSPVf6Z0",
                                "password": "",
                                "username": "",
                                "thumbnail": "d60cc0f0-97ab-11e5-a5dc-53f0fcbc3a18-CsfA4LyDGSPVf6Z0-thumbnail.jpg",
                                "manufacturer": "unknown",
                                "motionParams": {
                                    "roi": 1.111111111111111e+99,
                                    "enabled": true,
                                    "threshold": 120,
                                    "sensitivity": 50
                                },
                                "schedule_enabled": true
                            },
                            {
                                "ip": "10.10.0.127",
                                "name": "Kitchen",
                                "status": "offline",
                                "streams": [
                                    {
                                        "id": "38d7df81-166c-4d99-d754-a97d849f5082",
                                        "url": "rtsp://admin:admin@192.168.0.104/video1enc2",
                                        "name": "SD",
                                        "retention": "",
                                        "latestThumb": "1449739056000_11000"
                                    },
                                    {
                                        "id": "b8ba9496-8534-44fa-d44d-06978a001a23",
                                        "url": "rtsp://admin:admin@192.168.0.104/video1enc1",
                                        "name": "HD",
                                        "retention": "",
                                        "latestThumb": "1449768356000_17417"
                                    }
                                ],
                                "cameraId": "cNzA9Qw6aIU4K5jR",
                                "password": "",
                                "username": "",
                                "thumbnail": "d60cc0f0-97ab-11e5-a5dc-53f0fcbc3a18-cNzA9Qw6aIU4K5jR-thumbnail.jpg",
                                "manufacturer": "unknown",
                                "motionParams": {
                                    "roi": 1.111111111111111e+99,
                                    "enabled": true,
                                    "threshold": 152,
                                    "sensitivity": 50
                                },
                                "schedule_enabled": true
                            }
                        ],
                        "deviceInformation": {
                            "ip": "166.164.111.142",
                            "name": "RRChicagoAve 2",
                            "size": 3887985590272,
                            "used": 440392482816,
                            "model": "TS-X53",
                            "firmware": "4.2.0",
                            "port": 8080,
                            "deviceCapacity": 3887985590272,
                            "availableCapacity": 3447593107456,
                            "localIP": "10.1.1.2"
                        },
                        "$$hashKey": "object:549"
                    }
            }

+ Response 200 (application/json)

    + Body

            {
                "eventServerUrl": "https://myeventserver.com",
                "imageServerUrl": "https://myimageserver.com",
                "signallingServerUrl": "https://mysignallingserver.com",
                "checkinInterval": "3600",
                "updateUrl": "https://myupdateurl.com",
                "updateVersion": "v0.0.2"
                "overridePorts": {
                    "vms": 8080,
                    "uploader": 3000,
                    "checkin": 1234
                }
            }

## Group Licenses

## Activate [/api/licenses/activate]

When installing a Connect device, a license key is provided.  Providing this license key will hit this endpoint, which activates the license for that device and adds it to our /devices repository.

### Activate [POST]
+ Request (application/json)

        {
            "key": "161bc25962da8fed6d2f59922fb642aa",
            "username": "cwhiten",
            "password": "hunter2",
            "address": {
                "address_components": [
                {
                    'long_name': city,
                    'short_name':'Ottawa',
                    'types':[
                        'locality',
                        'political'
                    ]
                },
                {
                    'long_name':'Ottawa Division',
                    'short_name':'Ottawa Division',
                    'types':[
                        'administrative_area_level_2',
                        'political'
                    ]
                },
                {
                    'long_name': province,
                    'short_name':'ON',
                    'types':[
                        'administrative_area_level_1',
                        'political'
                    ]
                },
                {
                    'long_name': country,
                    'short_name':'CA',
                    'types':[
                        'country',
                        'political'
                    ]
                }
            ],
            "formatted_address": "390 March Road, Kanata, ON, H0H0H0"
        },
        "location": {
            "lat": 45.123,
            "lng": -75.222
        }

        }

+ Response 200 (application/json)

        {
            "authToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBfbWV0YWRhdGEiOnsidGVuYW50X2lkIjoiMSIsInVzZXJfdHlwZSI6IlN1cGVyQWRtaW4ifSwiZW1haWwiOiJjd2hpdGVuKzFAc29saW5rY29ycC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImlzcyI6Imh0dHBzOi8vc29saW5rLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1NWE2ODVjMjQ4OTdiM2FiMTAyNTUzMjgiLCJhdWQiOiI1UjlpREtpUTduWUNHT0phQkRyUGJlc013bmtHajdpaCIsImV4cCI6MTQzNzc5MzA4MCwiaWF0IjoxNDM3NzU3MDgwfQ.8yCltCoXpjAumpSiAZpFl55-rWwKTdZgQ8pOjFUCLsY",
            "refreshToken": "W4WhwYpXTBeBYuuNz7zBSBf8zZbkazQlLWkRmvaYMoSAM",
            "deviceId": "A4af23bij",
            "aws": {
                "accessKeyId": "cdr56yhjko987tfdxsergthjkiuytfgde456",
                "secretAccessKey": "vgt67u8iop0987ygfdr56yuio908uygfdr4567u8iklo098uhygtr567898uyhg",
                "sessionToken": "vfty67uikolp098ygfder45678987y6tgfdsertyuhjklo098iujh",
                "expiration": "1447788512"
            }
        }

## Group Authentication

## Login [/api/auth/login]

A user or connect device will post to the /auth/login endpoint to get a valid JWT token for future calls.

### Login [POST]
+ Request (application/json)

        {
            "username": "cwhiten@solinkcorp.com",
            "password": "test"
        }

+ Response 200 (application/json)

        {
            authToken: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBfbWV0YWRhdGEiOnsidGVuYW50X2lkIjoiMSIsInVzZXJfdHlwZSI6IlN1cGVyQWRtaW4ifSwiZW1haWwiOiJjd2hpdGVuKzFAc29saW5rY29ycC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImlzcyI6Imh0dHBzOi8vc29saW5rLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1NWE2ODVjMjQ4OTdiM2FiMTAyNTUzMjgiLCJhdWQiOiI1UjlpREtpUTduWUNHT0phQkRyUGJlc013bmtHajdpaCIsImV4cCI6MTQzNzc5MzA4MCwiaWF0IjoxNDM3NzU3MDgwfQ.8yCltCoXpjAumpSiAZpFl55-rWwKTdZgQ8pOjFUCLsY",
            refreshToken: "W4WhwYpXTBeBYuuNz7zBSBf8zZbkazQlLWkRmvaYMoSAM",
            aws: {
                accessKeyId: "ASIAIE3VWYBHAN32YG5Q",
                secretAccessKey: "UbILm6V9ip0gyUpw6kqDcet+PGFwrjBhmPa+Z6p2",
                sessionToken: "AQoDYXdzENr//////////wEawALgJc/SxMUbsxgIL5CGQcoGQmxF5wpV8ZuWQtwDYGngPfrXCHxoknbwxjwQOJPaK6N2rFtKoPw4ojJon1K9BQlNZnUQ4NSuPmTqDLZdltS+nrlUdZ/U8RWdFhoDtrJLL/aBsHBlymLPIR//JcuiCMnWZDtPpOIZVK92wZKllMunfnnpVz9LN/X6jkeX2NhMYRK+Q2dTH0Z7UuOgK+UMTW1/ayFECDGrVCctkmdR1Rr/cVA0yq8zF4k/SYar5WZIWQ1YLvSHT57/jD/lAUBOuBQ64gMwvXw8ptsRpl1c0xjWZn4azrMBz+FJAs2OTbcrl/arUF3YVLttH+aEIxHMamGYbUxqq3e7LOjKvnJbWFVWfdsrRaWMyaEIPYbVKOodRtlcsD+9p2qXtBr0eB48hBggxoir+P9yGNFeprgG7s/e/SCZ3cmtBQ=="
            }-
        }

## Validate [/api/auth/validate]

Validate whether a given JWT token is valid (not expired, matches secret, not revoked).
Returns a 200 if valid.  Otherwise, returns a 401.

### Validate [POST]
+ Request (application/json)

        {
            "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBfbWV0YWRhdGEiOnsidGVuYW50X2lkIjoiMSIsInVzZXJfdHlwZSI6IlN1cGVyQWRtaW4ifSwiZW1haWwiOiJjd2hpdGVuKzFAc29saW5rY29ycC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImlzcyI6Imh0dHBzOi8vc29saW5rLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1NWE2ODVjMjQ4OTdiM2FiMTAyNTUzMjgiLCJhdWQiOiI1UjlpREtpUTduWUNHT0phQkRyUGJlc013bmtHajdpaCIsImV4cCI6MTQzNzc5MzA4MCwiaWF0IjoxNDM3NzU3MDgwfQ.8yCltCoXpjAumpSiAZpFl55-rWwKTdZgQ8pOjFUCLsY",
        }

+ Response 200 (application/json)

        {
        }

## Refresh [/api/auth/refresh]

Generate a new authentication token from a user's refresh token.

### Refresh [POST]
+ Request (application/json)

        {
            "refreshToken": "W4WhwYpXTBeBYuuNz7zBSBf8zZbkazQlLWkRmvaYMoSAM",
            "jwtToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik56QTNPRUZHTWpoR1JrVTJNVVZFUlRsQk16Y3pOVFkxUlVVek56ZEJSVEV4TTBKRU1VTkdSUSJ9.eyJhcHBfbWV0YWRhdGEiOnsidGVuYW50SWQiOiI0MWE0MDJkMC02MTRhLTExZTUtYTZkZS0zNzdiYTQ3ZmRjYTkiLCJ1c2VyVHlwZSI6ImFkbWluIn0sImVtYWlsIjoiZGVtb0BjdXN0b21lci5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9zb2xpbmsuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDU2MDE4NzQwMjU1ZTEzNzg1MTQ1MzU4ZSIsImF1ZCI6IjVSOWlES2lRN25ZQ0dPSmFCRHJQYmVzTXdua0dqN2loIiwiZXhwIjoxNDQ1NTQzNzcwLCJpYXQiOjE0NDU1MjU3NzB9.noWYd8X3v3iTvdAT-F9rf97w4qfGKbxR6KW44L-xTwFA1zAXR8_s5XpuHGYo8dA9ImVZNMEUpWgHMc_dBz_1O19Rhun1X2fvZcn2EyLKkE7m_o7_6Y8DElYf5Pv_RDatHiyNM6aLkHJgKHqn8gKbAfs7Dt_E2G7V2B8GsUqzdC3XlWwiqdC6LIo81v3WjZ3CQuOR6-QGl-ogI0rn4YyxKGsZxsE3p4_ZzxpNV05KDdolKiJSaBY4qTwVSOec0_Xr8M8BPnqNkUpcmF6eFf6Lbp8b4QhEhY_-zZNymNyG6ect0dFeMTKBpHWfQw0u1qyfK0LmMY2Md2kW17aJtutXXA"
        }

+ Response 200 (application/json)

        {
            "auth_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBfbWV0YWRhdGEiOnsidGVuYW50X2lkIjoiMSIsInVzZXJfdHlwZSI6IlN1cGVyQWRtaW4ifSwiZW1haWwiOiJjd2hpdGVuKzFAc29saW5rY29ycC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImlzcyI6Imh0dHBzOi8vc29saW5rLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1NWE2ODVjMjQ4OTdiM2FiMTAyNTUzMjgiLCJhdWQiOiI1UjlpREtpUTduWUNHT0phQkRyUGJlc013bmtHajdpaCIsImV4cCI6MTQzNzc5MzA4MCwiaWF0IjoxNDM3NzU3MDgwfQ.8yCltCoXpjAumpSiAZpFl55-rWwKTdZgQ8pOjFUCLsY"
        }

## Set password [/api/auth/setpassword]

A request from the platform is sent out with user's current email, current password and new password

### Change Password [POST]
+ Request (application/json)

        {
            "email": "isharif@solinkcorp.com",
            "oldPassword": "old password",
            "newPassword": "new password"
        }

+ Response 202 (application/json)

        {
            "response": "Password successfully updated."
        }

## Forgot password [/api/auth/forgotpassword]

An email is sent to the user's current email to confirm changing the password

### Forgot Password [POST]
+ Request (application/json)

        {
            "email": "isharif@solinkcorp.com",
            "newPassword": "new password"
        }

+ Response 200 (application/json)

        {
            "response": "Forgot password email successfully sent."
        }

## Force set password [/api/auth/forceSetPassword]

Force set a user's password to a specific value

### Force Set Password [PUT]
+ Request (application/json)

        {
            "id": "auth0|5633b2d0794d1c5a0b72a79d",
            "password": "chrisrules"
        }

+ Response 200 (application/json)

        {
            "response": "Password successfully updated."
        }

## Create user [/api/auth/createUser]

Create a new user within our authentication service.
This API endpoint should be moved to a `/users` endpoint in a later migration.

### Create User [POST]
+ Request (application/json)

        {
            "email": "test@customer.com",
            "password": "solink",
            "userType": "admin",
            "orgId": "a3953d60-7f31-11e5-92b7-c9701c189e5f"
        }
+ Response 201 (application/json)

        {
            "response":{
                "email":"test@customer.com",
                "email_verified":true,
                "user_id":"auth0|5633b2d0794d1c5a0b72a79d",
                "picture":"https://s.gravatar.com/avatar/771aa3cf167856f1f2f0270bbf3c878f?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fte.png",
                "nickname":"test",
                "identities":[
                    {
                        "user_id":"5633b2d0794d1c5a0b72a79d",
                        "provider":"auth0",
                        "connection":"Username-Password-Authentication",
                        "isSocial":false
                    }
                ],
                "updated_at":"2016-02-16T15:53:35.971Z",
                "created_at":"2015-10-30T18:11:28.091Z",
                "name":"test@customer.com",
                "last_password_reset":"2015-11-12T22:42:03.443Z",
                "app_metadata":{
                    "tenantId":"a3953d60-7f31-11e5-92b7-c9701c189e5f",
                    "userType":"admin"
                },
                "last_ip":"52.35.201.87",
                "last_login":"2016-02-16T15:42:12.897Z",
                "logins_count":814
            }
        }

## Delete user [/api/auth/deleteUser]

Delete a user from our authentication service.
This API endpoint should be moved to a `/users` endpoint in a later migration.

### Delete User [DELETE]
+ Request (application/json)

        {
            "id": "auth0|5633b2d0794d1c5a0b72a79d"
        }

+ Response 204 (application/json)

## Update user metadata [/api/auth/updateUserMetadata]

A user's internal app_metadata is modified to reflect the property changes requested.  This is useful for changing a user's user type, assigning them to a subset of devices, or enabling and disabling certain functionality encoded in that user's JWT.
This API endpoint should be moved to a `/users` endpoint in a later migration.

### Update user metadata [PUT]
+ Request (application/json)

        {
            "id": "auth0|5633b2d0794d1c5a0b72a79d",
            "metadata": {
                "devices": ["abcdefg", "12345"],
                "wrtc": "true"
            }
        }

+ Response 200 (application/json)

        {
            "response":{
                "email":"test@customer.com",
                "email_verified":true,
                "user_id":"auth0|5633b2d0794d1c5a0b72a79d",
                "picture":"https://s.gravatar.com/avatar/771aa3cf167856f1f2f0270bbf3c878f?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fte.png",
                "nickname":"test",
                "identities":[
                    {
                        "user_id":"5633b2d0794d1c5a0b72a79d",
                        "provider":"auth0",
                        "connection":"Username-Password-Authentication",
                        "isSocial":false
                    }
                ],
                "updated_at":"2016-02-16T15:53:35.971Z",
                "created_at":"2015-10-30T18:11:28.091Z",
                "name":"test@customer.com",
                "last_password_reset":"2015-11-12T22:42:03.443Z",
                "app_metadata":{
                    "tenantId":"a3953d60-7f31-11e5-92b7-c9701c189e5f",
                    "userType":"admin",
                    "devices": [
                        "abcdefg",
                        "12345"
                    ]
                },
                "user_metadata":{
                    "wrtc": "true",
                },
                "last_ip":"52.35.201.87",
                "last_login":"2016-02-16T15:42:12.897Z",
                "logins_count":814
            }
        }

## Group Connectors

## Connectors [/api/connectors/{connectorId}/filter]

Connector object has the following attributes:
+ name - Filter name.
+ script - Javascript blob of the script for the listener
+ description - description of the script
+ lastUpdated - the date and time when the object last updated(through PUT/POST)


+ Parameters
    + connectorId: asdas-a2a5-11e5-9e4c-asdfasassdf (required, string) - The ID of the device


### Get Connector [GET]

+ Response 200 (application/json)

    + Body

            {
              "id": "41c47270-a28d-11e5-bad2-6fe88522b0fe",
              "name": "Motion Parser",
              "script": "console.log(String.fromCharCode(0xD83D, 0xDE32));",
              "description": null,
              "lastUpdated": "2016-01-19T17:03:09.000Z"
            }

## Camera [/api/cameras/{cameraId}]

Camera object has the following attributes:
+ name - the name of the camera.
+ status - shows if the camera is online or offline
+ deviceId - id of the QNAP device the camera is associated with
+ streams - array of streams present in the camera
+ thumbnail - url of the thumbnail of the camera


+ Parameters
    + cameraId: asdas-a2a5-11e5-9e4c-asdfasassdf (required, string) - The ID of the device


### Get Camera [GET]

+ Response 200 (application/json)

    + Body

            {
              "id": "25a82790-a4f8-11e5-94a2-fd50a5ff3026",
              "cameraId": "98ee3640-a2a5-11e5-9e4c-31c6c5024ea1",
              "name": "my camera",
              "status": "online",
              "deviceId": "98ee3640-a2a5-11e5-9e4c-31c6c5024ea1",
              "streams": [
                    "any"
                    ],
              "thumbnail": "thumbnail.jpeg"
            }


## Camera Assignment [/api/connectors/{connectorId}/cameraConnectors]

Camera assignment is done through the following methods.

+ Parameters
    + connectorId: b5084250-4b37-11e5-8184-752d1c0476b3 (required, string) - The ID of the device

### Assign Camera [POST]
+ Request (application/json)

        {
          "cameraId": "98ee3640-a2a5-11e5-9e4c-31c6c5024ea1",
        }

+ Response 200 (application/json)

        {
          "id": 5,
          "connectorId": "b5084250-4b37-11e5-8184-752d1c0476b3",
          "cameraId": "98ee3640-a2a5-11e5-9e4c-31c6c5024ea1"
        }

### Unassign Camera [DELETE]
+ Request (application/json)

        {
          "id": "98ee3640-a2a5-11e5-9e4c-31c6c5024ea1",
        }

+ Response 200 (application/json)

        {
          "id": 5,
          "connectorId": "b5084250-4b37-11e5-8184-752d1c0476b3",
          "cameraId": "98ee3640-a2a5-11e5-9e4c-31c6c5024ea1"
        }


### List Assigned Cameras [GET]
+ Response 200 (application/json)

        [
          {
            "cameraId": "25a82790-a4f8-11e5-94a2-fd50a5ff3026",
            "connectorId": "73fee340-a4dd-11e5-a1aa-5de1b344ce9b",
            "id": 3
          },
          {
            "cameraId": "25a82790-a4f8-11e5-94a2-fd50a5ff3026",
            "connectorId": "73fee340-a4dd-11e5-a1aa-5de1b344ce9b",
            "id": 4
          }
        ]

## Group Software Versions

Modify software version number used in clouds, resellers, tenants, and devices.

## Modifying specific versions [/api/softwareversions/{id}]

Remove, edit, or get specific software versions.

+ Parameters
    + id: 7d2c1010-b4b8-11e5-a32d-a56e80dc4179 - the ID of the version

### Edit latest software version [PUT]
+ Request (application/json)

        {
            "id": "7d2c1010-b4b8-11e5-a32d-a56e80dc4179",
            "name": "v.0.0.6",
            "code": 2,
            "url": "http://solink.softwareversion.test.com/test/software-version/v0.0.2/",
        }

+ Response 200 (application/json)

        {
             "id": "7d2c1010-b4b8-11e5-a32d-a56e80dc4179",
             "name": "v0.0.6",
             "code": 2,
             "url": "http://solink.softwareversion.test.com/test/software-version/v0.0.2/"
        }

### Delete software version [DELETE]
+ Response 200 (application/json)

        {
             count: 1
        }

### Get specific software version [GET]
+ Response 200 (application/json)

        {
            "id": "4bd2c330-b4a7-11e5-ae04-4ff0e0c012ca",
            "name": "v0.0.2",
            "code": 2,
            "url": "http://resources.solinkcloud.com/installers/solink-testing/v0.0.2/"
        }

## Getting or Adding [/api/softwareversions]

Get or add available software version numbers.

### Get all software versions [GET]
+ Response 200 (application/json)

    + Body

            [
                {
                    "id": "33721400-b491-11e5-ae4d-2db205d4c135",
                    "name": "v0.0.2",
                    "code": 2,
                    "url": "http://solink.softwareversion.test.com/test/software-version/v0.0.2/",
                },
                {
                    "id": "36ffcea0-b491-11e5-ae4d-2db205d4c135",
                    "name": "v0.0.2",
                    "code": 2,
                    "url": "http://solink.softwareversion.test.com/test/software-version/v0.0.2/",
                },
                {
                    "id": "4bd2c330-b4a7-11e5-ae04-4ff0e0c012ca",
                    "name": "v0.0.2",
                    "code":2 ,
                    "url": "http://solink.softwareversion.test.com/test/software-version/v0.0.2//",
                },
                {
                    "id": "7d2c1010-b4b8-11e5-a32d-a56e80dc4179",
                    "name": "v0.0.6",
                    "code": 2,
                    "url": "http://solink.softwareversion.test.com/test/software-version/v0.0.2/"
                }
            ]

### Add software version [POST]
+ Request (application/json)

        {
            "name": "v0.0.2",
            "code": 2,
            "url": "http://solink.softwareversion.test.com/test/software-version/v0.0.2/"
        }

+ Response 200 (application/json)

        {
            "id": "4bd2c330-b4a7-11e5-ae04-4ff0e0c012ca",
            "name": "v0.0.2",
            "code": 2,
            "url": "http://solink.softwareversion.test.com/test/software-version/v0.0.2/"
        }

## Group Report Associations

## Reports [/api/reports]

Report Connector will provide Reports assigned to a provided customer token.
It has the following attributes:
+ query - the report object
    + name - Report name.
    + filter - ElasticSearch syntax. Must be in valid JSON format.
    + description - description of the script
    + lastUpdated - the date and time when the report last updated(through PUT/POST)

### List available Reports [GET]

+ Response 200 (application/json)

    + Body

            [
              {
                "query": {
                  "id": "6152b650-c534-11e5-b06d-cb4d92913333",
                  "filter": {
                    "hello": "hello2"
                  },
                  "name": "Test Filter",
                  "description": "Hello world.",
                  "lastUpdated": "2016-01-27T20:27:26.000Z"
                }
              },
              {
                "query": {
                  "id": "6152b650-c534-11e5-b06d-cb4d92913333",
                  "filter": {
                    "hello": "hello2"
                  },
                  "name": "Test Filter",
                  "description": "Hello world.",
                  "lastUpdated": "2016-01-27T20:27:26.000Z"
                }
              }
            ]

## Create a Report [/api/searchfilters]




###Group Configuration

## Retrieve IP [/api/configuration/whatismyip]


### Get IP Address [GET]

 + Response 200 (application/json)

     + Body

             "207.35.173.122"
